---
# Reuse validation logic.
- import_tasks: "{{ role_path }}/../validate/tasks/validate_tails_environment.yml"

- import_tasks: cleanup_legacy_artifacts.yml

- import_tasks: migrate_existing_config.yml

- import_tasks: copy_dotfiles.yml

- import_tasks: configure_torrc_additions.yml

- import_tasks: create_desktop_shortcuts.yml

- import_tasks: configure_network_hook.yml

- name: Check that we are on an admin workstation
  stat:
    path: group_vars/all/site-specific
  register: site_specific_result

- include_tasks: create_ssh_aliases.yml
  when: site_specific_result.stat.exists
