---
- import_tasks: post_ubuntu_install_checks.yml

- import_tasks: create_users.yml

- import_tasks: setup_etc_hosts.yml

- import_tasks: harden_dns.yml

- import_tasks: install_tmux.yml

- import_tasks: install_ntp.yml

- import_tasks: cron_apt.yml
  tags:
    - reboot

- import_tasks: apt_upgrade.yml

- import_tasks: sysctl.yml

- import_tasks: disable_swap.yml

- import_tasks: remove_kernel_modules.yml
