---
- name: Add xenial apt repository for openjdk8-jre
  copy:
    src: "archive.ubuntu.xenial.list"
    dest: "/etc/apt/sources.list.d/archive.ubuntu.xenial.list"
    owner: "root"
    group: "root"
    mode: "0644"
  become: yes

- name: Copy apt preferences to bump openjdk-8-jre-headless and nothing else
  copy:
    src: "preferences"
    dest: "/etc/apt/preferences"
    owner: "root"
    group: "root"
    mode: "0644"
  become: yes
