---
- block:
  - name: Install securedrop-signal-cli package from FPF repo.
    apt:
      pkg: securedrop-signal-cli
      state: latest
      update_cache: yes
    tags:
      - apt

  - name: Convert jvm header for pax
    shell: "paxctl -c /usr/lib/jvm/java-7-openjdk-amd64/bin/java"
    become: yes

  - name: Set jvm pax flag
    shell: "paxctl -m /usr/lib/jvm/java-7-openjdk-amd64/bin/java"
    become: yes

  become: True
