---
- include: install_xenial_repo.yml
  when: signal_cli_register
  
- include: install_signal_cli.yml
  when: signal_cli_register

- include: register_signal_number.yml
  when: signal_cli_register

- include: copy_signal-cli_config.yml
  when: signal_cli_copy_config

- include: signal-cli_post_install.yml
  when: signal_destination_number
