---
- name: Signal-cli test notification
  command: '/usr/local/bin/signal-cli --config /etc/signal/ -u {{ signal_number }} send -m "This is a test message!" {{ signal_destination_number }}'
  become: yes

- name: Signal-cli get safety number
  command: '/usr/local/bin/signal-cli --config /etc/signal -u {{ signal_number }} listIdentities -n {{ signal_destination_number }}'
  become: yes
  register: signal_safety_number

- name: Retrieve signal_cli safety number
  copy:
    dest: "{{ playbook_dir }}/{{ signal_number }}.safetynumber"
    content: "{{ signal_safety_number.stdout }}"
  delegate_to: localhost
  become: "no"
