---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    molecule_file: "{{ lookup('env', 'MOLECULE_FILE') }}"
    molecule_ephemeral_directory: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}"
    molecule_scenario_directory: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}"
    molecule_yml: "{{ lookup('file', molecule_file) | from_yaml }}"
    # sha256 digest of quay.io/freedomofpress/sd-docker-builder:2018_05_22
    image_hash: 0f9550c0d33af7883afbb24ee560fc7f6db3f5e8005ff3f086420499fc51ef0d
  tasks:
    - name: Create builders
      docker_container:
        name: "{{ item.name }}"
        hostname: "{{ item.name }}"
        image: "quay.io/freedomofpress/sd-docker-builder@sha256:{{image_hash}}"
        state: started
        command: "tail -f /dev/null"
        privileged: "{{ item.privileged | default(omit) }}"
        volumes: "{{ item.volumes | default(omit) }}"
        capabilities: "{{ item.capabilities | default(omit) }}"
      with_items: "{{ molecule_yml.platforms }}"
