---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    molecule_file: "{{ lookup('env', 'MOLECULE_FILE') }}"
    molecule_ephemeral_directory: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}"
    molecule_scenario_directory: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}"
    molecule_yml: "{{ lookup('file', molecule_file) | from_yaml }}"
    image_hash: e9f1683b1fe756751e3ec6481860414988eceaa25663e2e98dd5223e6c3b2856
  tasks:
    - name: Create builders
      docker_container:
        name: "{{ item.name }}"
        hostname: "{{ item.name }}"
        image: "quay.io/freedomofpress/sd-docker-builder@sha256:{{image_hash}}"
        state: started
        command: "tail -f /dev/null"
        privileged: "{{ item.privileged | default(omit) }}"
        volumes: "{{ item.volumes | default(omit) }}"
        capabilities: "{{ item.capabilities | default(omit) }}"
      with_items: "{{ molecule_yml.platforms }}"
